live_config_reload = true

import = [
  "~/.config/alacritty/themes/tokyo_night.toml"
]

[bell]
animation = "EaseOutExpo"
duration = 0

[env]
TERM = "xterm-256color"

[font]
size = 13

[shell]
program = "/bin/zsh"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "full"
dynamic_title = true
startup_mode = "Maximized"
option_as_alt = "Both"

[window.dimensions]
columns = 120
lines = 60

[window.padding]
x = 4
y = 4
